apiVersion: 1

datasources:
  - name: InfluxDB-Fleet
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: fleet-org
      defaultBucket: fleet-telemetry
    secureJsonData:
      token: fleet-super-secret-token-001
    isDefault: true
    editable: true
